name: train_slot_dynamics
img_size: &img_size 128
shape_meta: &shape_meta
  obs:
    agentview_rgb:
      shape: [3, *img_size, *img_size]
      type: rgb
    ee_pos:
      shape: [3]
    ee_ori:
      shape: [4]
    gripper_states:
      shape: [2]
  action:
    shape: [7]
    
dataset:
  dataset_path: data/libero/libero_10
  shape_meta: *shape_meta
  seq_len: 8
  frame_stride: 1
  val_ratio: 0.05

model:
  num_slots: 8
  slot_dim: 64
  resolution: [*img_size, *img_size]
  num_iterations: 5
  num_layers: 4
  num_heads: 4
  ff_mult: 4
  dropout: 0.1

optimizer:
  lr: 4e-4
  betas: [0.9, 0.995]
  weight_decay: 1e-4
  lr_scheduler: cosine
  lr_warmup_steps: 10000

loss:
  w_recon: 1.0
  w_consist: 0.1

train:
  debug: False
  seed: 42
  device: cuda:1
  batch_size: 8
  num_workers: 0
  num_epochs: 500
  val_every: 10
  ckpt_every: 10
  save_last_ckpt: True
  vis_every: 10
  vis_n: 2
  use_amp: True
  amp_dtype: float16
  grad_clip: 1.0
  use_grad_scaler: True

logging:
  output_dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
  project: Slot
  name: ${name}
  mode: online
  tag: ["${name}"]

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
  sweep:
    dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
    subdir: ${hydra.job.num}