name: train_slot_ae
img_size: &img_size [128, 128]

dataset:
  dataset_path: data/libero/libero_10
  view: agentview_rgb
  resize: ${img_size}
  frame_stride: 3

model:
  num_slots: 7
  num_iterations: 3
  resolution: ${img_size}

train:
  seed: 42
  device: cuda:0
  batch_size: 32
  num_workers: 0
  val_ratio: 0.05  
  lr: 4e-4
  lr_scheduler: cosine
  lr_warmup_steps: 10000
  num_epochs: 500
  val_every: 10
  ckpt_every: 10
  save_last_ckpt: True
  vis_every: 10
  vis_n: 2
  use_amp: True
  amp_dtype: float16
  grad_clip: 1.0
  use_grad_scaler: True

logging:
  output_dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
  project: Slot
  name: ${name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
  sweep:
    dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
    subdir: ${hydra.job.num}