name: train_slot_ae
img_size: &img_size 128
shape_meta: &shape_meta
  obs:
    agentview_rgb:
      shape: [3, *img_size, *img_size]
      type: rgb
    eye_in_hand_rgb:
      shape: [3, *img_size, *img_size]
      type: rgb
    ee_pos:
      shape: [3]
    ee_ori:
      shape: [4]
    gripper_states:
      shape: [2]
  action:
    shape: [7]
    
dataset:
  dataset_path: data/libero/libero_10
  shape_meta: *shape_meta
  seq_len: 8
  frame_stride: 1
  val_ratio: 0.05

model:
  num_slots: &num_slots 8
  slot_dim: &slot_dim 64
  encoder:
    in_channels: 3
    hidden_dim: 128
    num_slots: *num_slots
    slot_dim: *slot_dim
    num_iterations: 3
    mlp_hidden_dim: 256
    resolution: [*img_size, *img_size]
  dynamics:
    slot_dim: *slot_dim
    num_layers: 4
    num_heads: 4
    ff_dim: 512
    dropout: 0.1
  event_detector:
    num_slots: *num_slots
    slot_dim: *slot_dim
    window: 6
    hidden_dim: 256

optimizer:
  lr: 4e-4
  weight_decay: 1e-4
  lr_scheduler: cosine
  lr_warmup_steps: 10000

loss:
  rel_weight: 0.5
  soft_label_temp: 5.0
  ot_temp: 0.2
  sinkhorn_iters: 20
  beta_sparsity: 1e-3
  lambda_evt: 1.0
  lambda_cv: 0.5
  lambda_rel: 0.3


train:
  debug: False
  seed: 42
  device: cuda:1
  batch_size: 8
  num_workers: 0
  num_epochs: 500
  val_every: 10
  ckpt_every: 10
  save_last_ckpt: True
  reference_view: agentview_rgb
  use_amp: True
  amp_dtype: float16
  grad_clip: 1.0
  use_grad_scaler: True

logging:
  output_dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
  project: Slot
  name: ${name}
  mode: online
  tag: ["${name}"]

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
  sweep:
    dir: data/outputs/${now:%Y_%m_%d_%H_%M_%S}_${name}
    subdir: ${hydra.job.num}