_target_: slot.model.feature_extractor.clip_extractor.CLIPImageFeatureExtractor
model_type: ViT-B/32    # 'RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px'
freeze: True
device: ${training.device}